// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLm9HJxaqjf2LhCbEb9-kBVThJeMGEQd8',
    appId: '1:960212867626:web:753ef28fd71c6024440153',
    messagingSenderId: '960212867626',
    projectId: 'wise-groove-380300',
    authDomain: 'wise-groove-380300.firebaseapp.com',
    storageBucket: 'wise-groove-380300.appspot.com',
    measurementId: 'G-LQZ43VCG4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfiuTn49oTMEKEG856DVWB_s5d3vkcgl4',
    appId: '1:960212867626:android:28d40a031128fe3d440153',
    messagingSenderId: '960212867626',
    projectId: 'wise-groove-380300',
    storageBucket: 'wise-groove-380300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAX7VAwIgdg5Z9Un3dqDxQyIHNYJuiKvQ',
    appId: '1:960212867626:ios:dcb9ed22ca45f902440153',
    messagingSenderId: '960212867626',
    projectId: 'wise-groove-380300',
    storageBucket: 'wise-groove-380300.appspot.com',
    iosClientId: '960212867626-3e2k3tmc9adue3j6i4gdbipm6pp4s555.apps.googleusercontent.com',
    iosBundleId: 'com.skoni.crow.ghanama.ss.skoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAX7VAwIgdg5Z9Un3dqDxQyIHNYJuiKvQ',
    appId: '1:960212867626:ios:dcb9ed22ca45f902440153',
    messagingSenderId: '960212867626',
    projectId: 'wise-groove-380300',
    storageBucket: 'wise-groove-380300.appspot.com',
    iosClientId: '960212867626-3e2k3tmc9adue3j6i4gdbipm6pp4s555.apps.googleusercontent.com',
    iosBundleId: 'com.skoni.crow.ghanama.ss.skoni',
  );
}
